<script type="text/javascript">
var LHCFAQOptions = {status_text:'FAQ',url:'replace_me_with_dynamic_url',identifier:''};
(function() {
var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
po.src = '//fastfen.club/helper/index.php/rus/faq/getstatus/(position)/middle_right/(top)/0/(units)/percents/(theme)/1';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>
